#include <string>
#ifndef MCFUNCTION_H
#define MCFUNCTION_H

enum MCFunctionEvent { WORLD_FUNC, WORLD_LOAD, WORLD_TICK };

class MCFunction {
public:
	MCFunction(std::string funcName): FuncName(funcName) { SetName(funcName); }

public:
	MCFunctionEvent Event = MCFunctionEvent::WORLD_FUNC;

	std::string FuncName;
	std::string Content = "";

	void SetName(std::string funcName) {
		this->FuncName = funcName;
		Content = "";
		AppendLine(std::string("# !") + funcName + ".mcfunction");
		AppendLine("# file generated by Luamc2Datapack (MCDataKit)\n");
	}

	void Append(std::string data) { Content += data; }
	void AppendLine(std::string data) { Content += data + "\n"; }
};

#endif // !MCFUNCTION_H
